title: Tim Sodeinde
logo: IMG_20231104_084645_136.jpg
description: Data analyst with experience using microsoft excel for reprt automation, sql for data manipulation and interrogation.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
