title: Tim Sodeinde
logo: IMG_20231104_084645_136.jpg
description: Analytical and detail oriented Data Analyst with experience using microsoft excel for report automation, sql for data manipulation and interrogation and Power BI for visualization.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
